### PR TITLE
Keep fetched bibentries on fetch error

### PR DESCRIPTION
**Pull request by cgogolin**

### CODE REVIEW

**Comment by cgogolin** [comment]
The idea to do such caching is good, but the present change is not how this should be implemented because in this way persistent errors on fetching will just never be recorded and thus never show up and never be noticed.

**Comment by cgogolin** [comment]
The new implementation should do the trick and also be backward compatible with values written to the data base with the old version.

The behavior I aim for is the following: Always keep the data from the last "successful" fetch operation even if a refresh results in an error. Display appropriate messages in case even the last good fetch returned no results. Display appropriate error messages in case the last fetch attempt resulted in an error (this could be a timeout or an error parsing the returned json, or...). Also display all error on the meta-data explorer page in the admin area.

**Comment by cgogolin** [comment]
@johannesjmeyer : This is a slightly non trivial update. In case you have the time to give it a look I would be very happy. If not, I think I know what I am doing :-)

**Comment by johannesjmeyer** [comment]
I'll have a look tomorrow!

**Comment by cgogolin** [comment]
Thanks for the review and the suggestion!

I was worried about code duplication as well. The problem is, to remove the duplicate code I would need to introduce a function that takes a callable as argument (which would have to tbe O3PO_Crossref::get_cited_by_bibentries or O3PO_Ads::get_cited_by_bibentries) and return at least three values. I am not sure that's worth it...

**Comment by johannesjmeyer** [comment]
I don't know if that's a big hassle in PHP. But if you add more citation sources, then it's probably worth it.

**Pull request merged**
